name: follower_x
description: "Follower X - تطبيق خدمات التواصل الاجتماعي"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # المكتبات الأساسية المستخدمة في الكود
  http: ^1.2.0
  shared_preferences: ^2.2.2

  # الأيقونات الأساسية
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # في حال أردت إضافة صور أو خطوط مستقبلاً يمكنك إلغاء تعليق الأسطر التالية:
  # assets:
  #   - assets/images/
