name: Build APK Automatically

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      # إنشاء مجلد الأندرويد تلقائياً
      - name: Generate Android Files
        run: flutter create . --platforms=android --org com.followerx.app

      # تثبيت المكتبات
      - name: Install Dependencies
        run: flutter pub get

      # بناء ملف APK
      - name: Build Release APK
        run: flutter build apk --release

      # رفع الملف المحدث إلى الإصدار v4
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
